<!--
 * @Author:luisa xiao
 * @Date: 2020-02-14 17:03:06
 * @LastEditTime: 2020-05-26 10:24:43
 * @LastEditors: Please set LastEditors
 * @Description: 小编程，大知识
 * @FilePath: /rm-portal/work/xly/project/serious-review/src/summary/面试相关/趣味编程题.md
 -->

<!--待续。。。。。-->
### code 1
```
    var foo = function bar () {
      return 12
    }
    console.log(typeof bar())
```

答案：输出是抛出异常，bar is not defined。

解析：这种命名函数表达式函数只能在函数体内有效


### code 2
```
    function f () {
      return f;
    }

    console.log(new f() instanceof f)
```

答案： false
解析：
a instanceof b 用于检测a是不是b的实例。如果题目f中没有return f,则答案明显为true;而在本题中new f()其返回的结果为f的函数对象，其并不是f的一个实例。

### code 3
```
  var a = {n:1}
  var b = a;
  a.x = a = {n:2}

  console.log(b,a)

```
答案： {n:1,x:{n:2}}, {n:2}
解析：执行时根据运算符的优先级，先执行a.x，此时a.x引用的是{n:1},然后表达式再从右往左执行

### code 4

```
  var name = "Tom";
  (function(){
    if(typeof name == 'undefined'){
      var name = 'jack'
      console.log('Good' + name)
    } else {
      console.log('Hello' + name)
    }
  })();
```
答案： Good jack 
解析：


### code 5

```
  const person = {name: "Jon"};

  function sayHi(age) {
    return `${this.name} is ${age}`
  }

  console.log(sayHi.call(person, 5))
  console.log(sayHi.bind(person, 5))
```

答案： Jon is 5，  function
解析：
俩者都可以传递我们想要this关键字引用的对象。但是call和apply方法会立即执行！bind方法会返回函数的拷贝值，但带有绑定的上下文！他不会立即执行。

### code 6

```
  const num = {
    a: 10,
    add(){
      return this.a + 2;
    },
    reduce: () => {
      this.a -2;
    }
  }
  console.log(num.add())
  console.log(num.reduce())
```
答案： 12 NaN
解析：add是普通函数，reduce是箭头函数，对于箭头函数，·this· 关键字指向的是它所在上下文的环境

### code 7
```
  var x = 1
  if(function f(){}) {
      x+= typeof f;
  }
  console.log(x)
```
答案：1undefined
解析：

### code 8

```
  const obj = {
    '2': 3,
    '3': 4,
    'length': 2,
    'splice': Array.prototype.splice,
    'push': Array.prototype.push
  }

  obj.push(1)
  obj.push(2);

  console.log(obj)
```

答案： Object(4) [empty × 2, 1, 2, splice: ƒ, push: ƒ]
解析：push方法和call()或者apply()一起使用时，可应用在类数组的对象上，push方法根据length属性来决定从哪里开始插入给定的值。如果length不能被转换成一个数值或者不存在，则插入的元素索引为0，当length不存在时，将会创建它。
在这题当中，push(1)时，此时length被定义为2，所以会从obj中索引为2的地方插入，由于‘2’已经被定义，因此会直接替换‘2’的值，push(2)同理。因为只定义了2和3俩项，所以索引0和1是empty。


### code 9
```
  function test(){};
  const a = test.prototype;
  const b = Object.getPrototypeOf(test);
  console.log(a === b)
```

答案：false
解析:  Object.getPrototypeOf(new test()) === test.prototype //true,
Object.getPrototypeOf是test函数的原型，test.prototype是使用new创建的test实例的原型。

### code 10
```
  let x,y;
  try {
    throw new Error();
  } catch (x) {
    x = 1;
    y = 2;
    console.log(x)
  }
console.log(x)
console.log(y)
```

答案：1  undefined 2
解析：catch块接收参数x，当我们传递参数时，这与变量的x不同。这个变量x是属于catch作用域的。需要注意的是catch的作用域，其实并不是常见的块作用域，并不能绑定自己的内部声明的变量。catch创建的块作用域，只对catch的参数有效。对于在内部声明的变量，catch并没有创建一个新的作用域，只是一个普通的代码块。


### code 11
```
  function myFn(n,o){
    console.log(n,o)
    return {
      myFn:function(m) {
        return myFn(m,n)
      }
    }
  }
```